package deaddrop

import (
	"crypto/sha256"
	"fmt"
	"io/fs"
	"strings"
	"testing"
)

func TestEmbeddedWebBundleContainsEntryAndManifest(t *testing.T) {
	web := WebFS()
	index, err := fs.ReadFile(web, "index.html")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(index), "Dead Drop") {
		t.Fatal("embedded index is not the Dead Drop entry point")
	}
	manifest, err := fs.ReadFile(web, "SHA256SUMS")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(manifest), "  js/app.js\n") {
		t.Fatal("embedded integrity manifest does not cover app.js")
	}
}

// TestEmbeddedBundleCoversEveryManifestEntry is the regression guard for the
// `all:` embed prefix. SHA256SUMS is generated by walking web/ on disk, so
// without it the manifest happily lists files (_crystals.js, _u64.js) that the
// binary never serves: the client 404s and /verify.html reports phantom drift.
//
// The same check runs at the command line as `deaddrop doctor`, so this asserts
// the shipped implementation rather than a copy of it.
func TestEmbeddedBundleCoversEveryManifestEntry(t *testing.T) {
	if err := VerifyEmbeddedBundle(); err != nil {
		t.Fatalf("embedded bundle does not match its manifest: %v", err)
	}
}

// A manifest listing a file the binary does not serve is the exact failure the
// "all:" prefix caused, so the checker has to notice it rather than skip it.
func TestVerifyEmbeddedBundleRejectsAMissingFile(t *testing.T) {
	web := WebFS()
	manifest, err := fs.ReadFile(web, "SHA256SUMS")
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for _, line := range strings.Split(strings.TrimSpace(string(manifest)), "\n") {
		if _, name, found := strings.Cut(line, "  "); found {
			names = append(names, name)
		}
	}
	if len(names) < 5 {
		t.Fatalf("manifest covers only %d files; expected the whole bundle", len(names))
	}
	// Every listed name must resolve, which is what makes the checker meaningful.
	for _, name := range names {
		if _, err := fs.ReadFile(web, name); err != nil {
			t.Errorf("manifest lists %q but the binary does not serve it: %v", name, err)
		}
	}
	// And every served file must hash to what the manifest claims.
	for _, line := range strings.Split(strings.TrimSpace(string(manifest)), "\n") {
		want, name, _ := strings.Cut(line, "  ")
		data, err := fs.ReadFile(web, name)
		if err != nil {
			continue
		}
		if got := fmt.Sprintf("%x", sha256.Sum256(data)); got != want {
			t.Errorf("%s: embedded bytes hash %s, manifest says %s", name, got, want)
		}
	}
}
