package deaddrop

import (
	"crypto/sha256"
	"fmt"
	"io/fs"
	"strings"
	"testing"
)

func TestEmbeddedWebBundleContainsEntryAndManifest(t *testing.T) {
	web := WebFS()
	index, err := fs.ReadFile(web, "index.html")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(index), "Dead Drop") {
		t.Fatal("embedded index is not the Dead Drop entry point")
	}
	manifest, err := fs.ReadFile(web, "SHA256SUMS")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(manifest), "  js/app.js\n") {
		t.Fatal("embedded integrity manifest does not cover app.js")
	}
}

// TestEmbeddedBundleCoversEveryManifestEntry is the regression guard for the
// go:embed "all:" prefix. SHA256SUMS is generated by walking web/ on disk, so
// without it the manifest happily lists files (_crystals.js, _u64.js) that the
// binary never serves: the client 404s and /verify.html reports phantom drift.
func TestEmbeddedBundleCoversEveryManifestEntry(t *testing.T) {
	web := WebFS()
	manifest, err := fs.ReadFile(web, "SHA256SUMS")
	if err != nil {
		t.Fatal(err)
	}
	for _, line := range strings.Split(strings.TrimSpace(string(manifest)), "\n") {
		want, name, found := strings.Cut(line, "  ")
		if !found {
			t.Fatalf("malformed manifest line %q", line)
		}
		data, err := fs.ReadFile(web, name)
		if err != nil {
			t.Errorf("manifest lists %q but the binary does not serve it: %v", name, err)
			continue
		}
		if got := fmt.Sprintf("%x", sha256.Sum256(data)); got != want {
			t.Errorf("%s: embedded bytes hash %s, manifest says %s", name, got, want)
		}
	}
}
