package deaddrop

import (
	"crypto/sha256"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"strings"
)

// embeddedWeb contains the exact browser client compiled into the server
// binary. Runtime edits to the checkout therefore cannot silently change the
// cryptography delivered by an already-audited binary.
//
// The all: prefix is load-bearing: a bare "web" pattern silently drops every
// file whose name starts with "_" or ".", which would leave the vendored
// ML-KEM dependencies (_crystals.js, _u64.js) out of the binary and 404 the
// entire post-quantum handshake at runtime.
//
//go:embed all:web
var embeddedWeb embed.FS

// WebFS returns the embedded browser bundle rooted at web/.
func WebFS() fs.FS {
	sub, err := fs.Sub(embeddedWeb, "web")
	if err != nil {
		panic("embedded web bundle is missing: " + err.Error())
	}
	return sub
}

// VerifyEmbeddedBundle re-derives every hash in the embedded SHA256SUMS from
// the embedded bytes.
//
// The manifest is generated by walking web/ on disk, so it describes the tree
// at build time; this asks the only question that matters afterwards, which is
// whether the binary now running serves exactly what its own manifest claims.
// A build from a tampered checkout, or an embed pattern that quietly dropped a
// file, both show up here rather than as a 404 in someone's browser.
func VerifyEmbeddedBundle() error {
	web := WebFS()
	manifest, err := fs.ReadFile(web, "SHA256SUMS")
	if err != nil {
		return fmt.Errorf("embedded integrity manifest is missing: %w", err)
	}

	var problems []error
	var checked int
	for _, line := range strings.Split(strings.TrimSpace(string(manifest)), "\n") {
		if line == "" {
			continue
		}
		want, name, found := strings.Cut(line, "  ")
		if !found {
			problems = append(problems, fmt.Errorf("malformed manifest line %q", line))
			continue
		}
		data, err := fs.ReadFile(web, name)
		if err != nil {
			problems = append(problems, fmt.Errorf("%s: listed but not served: %w", name, err))
			continue
		}
		if got := fmt.Sprintf("%x", sha256.Sum256(data)); got != want {
			problems = append(problems, fmt.Errorf("%s: serves %s, manifest says %s", name, got, want))
			continue
		}
		checked++
	}
	if checked == 0 && len(problems) == 0 {
		return errors.New("embedded integrity manifest is empty")
	}
	return errors.Join(problems...)
}

// BundleDigest is a single fingerprint for the client this binary serves: the
// SHA-256 of its own integrity manifest, which in turn names every file and its
// hash. One value to compare, rather than thirty-eight.
func BundleDigest() (string, error) {
	manifest, err := fs.ReadFile(WebFS(), "SHA256SUMS")
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", sha256.Sum256(manifest)), nil
}
