package srp

import (
	"encoding/hex"
	"math/big"
	"testing"
)

// Vectors generated by `node test/srp.selftest.mjs --vectors` — they prove the Go
// server and the browser client (web/js/srp.js) speak the identical protocol.
const (
	vUsername = "alice"
	vPassword = "correct horse battery staple"
	vSaltHex  = "000102030405060708090a0b0c0d0e0f"
	vAHex     = "0914aa31a45407b84e6e07c09ef9ef9b6aabcb6042823d8bf2e84edc03017ee071a7eab252e5dcbd9e0bed2ac2f47a048aaf7c1c681fa8f0617194948b226d5fa1c50b64bc6c82e62f8bd938e4bfabca49fe8e5cc2ba95533b1ba32108f66da74ff3728152532d34637e61760a2d32e7b4f60dbad3f5d35e4bda729739266021259c74f20385cc1fe322b8d5adaaf75c0efc250c4799b5a968e3bc504a121718309ae093c52e80cae42d7ce6e67cfb13d7234cd25fa1f5149810be0100087b3dce2ff4f655bae43582793c60795b486338341b56de7b579414221bf0d3c0b2b687d6732647edc3f432302aa824cb8bd1600b880ef1808d15cf40ec7ba47257fa"
	vBHex     = "036790ce301e155d93c8a4cab39f5f72a4f92e01f1842b52641b3696172f76e578f9a2463b8c4c77474311ef141696502aabdf1b059db0a95c2ebaa1ce80bf99fbc848a6e4f503d844cfcfcdbba75beaad94c7dc173ee580d34a09e3a12d120b032275f58f594c4ada1a0ae5bcd127aa1ef1da6f1242422353c3e13f2dde95983df6111520af7d65c671ae0980fa0d370c4e39e0936ee1eb29aeb73ca9d52947598d34734050bbc3ee401c2b790c82c3e9cdbc651be8238c9d8255438ce7e12d5f7d0e7b8a377e6c2faedd7c3ae42dcb5a10d8ceaf0bdb6a1545db050bb9190fe4c4fe892e1530b9651722e82593e39d4eb373b8879fb8453c4029363cb16d9e"
	vBbHex    = "6465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f80818283"
	vVHex     = "0953ca7a7d5daf328e7766a35e5465a99edbf6ca7b5ae4bf15b43304343c4848d32e12d6a371bc71c18940454017b43ded483d60f55e3133bab1d773af00a05652a90903ef1c4dee81e3f43d9250fee6f400bebb5efc32ce011f42de1775fca2bd2a65e80e29932c1917b2ad81fdec108415189f56f88dd12a8d9add90f57c2ffc47f12fe229195f02cd56252d81436ff21fad80fc09da99f16f054f8b7b7dd21c73b60d72e81a6c0b8e3470c70851bd02a30e50fbae8946029aae5bb2152dc67310b5391c258931bd2222447b4c3006ccca6d3b93f69ad86255b42fb90dc3c4cd087d7b9d60c8ba27848580228a2ca6b922ee7e18a4ee0e2ccb9bb86cd8a91d"
	vM1Hex    = "3f6ccdd2c124701cc312ac8a728d0e7afc31804bd27bfcc1ba91a4b5d184f7ea"
	vM2Hex    = "19824f6ec5869917f2d6381c137785ef14e5e8bc78bcb55970fae31848cdf373"
	vKHex     = "3fde1f8980f5a38d5a67113dd223e748131b7d9186c8ad7d0b79879f1bc26d86"
)

func TestCrossImplVectors(t *testing.T) {
	salt := mustBytes(t, vSaltHex)

	// Verifier must match the browser's.
	v := Verifier(vUsername, vPassword, salt)
	if got := v.Text(16); got != trimLead(vVHex) {
		t.Fatalf("verifier mismatch with JS client")
	}

	// Server B from the fixed b must match the browser's view.
	b := mustBig(t, vBbHex)
	B := new(big.Int).Mod(new(big.Int).Add(new(big.Int).Mul(k, v), new(big.Int).Exp(g, b, N)), N)
	if B.Text(16) != trimLead(vBHex) {
		t.Fatalf("server B mismatch with JS client")
	}

	// The decisive interop check: feed the JS client's A and M1 to the Go server.
	c := &Challenge{b: b, Bpub: B, v: v}
	A := mustBig(t, vAHex)
	M2, K, err := c.Verify(A, mustBytes(t, vM1Hex))
	if err != nil {
		t.Fatalf("Go server rejected JS client proof: %v", err)
	}
	if hex.EncodeToString(M2) != vM2Hex {
		t.Errorf("M2 mismatch: server and JS client disagree")
	}
	if hex.EncodeToString(K) != vKHex {
		t.Errorf("session key K mismatch between server and JS client")
	}
}

func TestGoRoundTrip(t *testing.T) {
	username, password := "bob", "hunter2-hunter2"
	salt := []byte("sixteen-byte-slt")
	v := Verifier(username, password, salt)

	c, err := NewChallenge(v)
	if err != nil {
		t.Fatal(err)
	}
	A, M1, expectM2, clientK := clientProof(t, username, password, salt, c.Bpub)
	M2, K, err := c.Verify(A, M1)
	if err != nil {
		t.Fatalf("server rejected honest client: %v", err)
	}
	if hex.EncodeToString(M2) != hex.EncodeToString(expectM2) {
		t.Error("client could not authenticate server (M2)")
	}
	if hex.EncodeToString(K) != hex.EncodeToString(clientK) {
		t.Error("session keys differ")
	}
}

func TestRejectsWrongPassword(t *testing.T) {
	v := Verifier("bob", "right-password", []byte("sixteen-byte-slt"))
	c, _ := NewChallenge(v)
	A, M1, _, _ := clientProof(t, "bob", "WRONG-password", []byte("sixteen-byte-slt"), c.Bpub)
	if _, _, err := c.Verify(A, M1); err != ErrProof {
		t.Fatalf("expected ErrProof for wrong password, got %v", err)
	}
}

func TestRejectsAZeroModN(t *testing.T) {
	v := Verifier("bob", "pw", []byte("sixteen-byte-slt"))
	c, _ := NewChallenge(v)
	if _, _, err := c.Verify(N, make([]byte, 32)); err != ErrBadParam { // A = N ≡ 0
		t.Fatalf("expected ErrBadParam for A ≡ 0, got %v", err)
	}
}

// clientProof mirrors web/js/srp.js for the Go-only round-trip tests.
func clientProof(t *testing.T, username, password string, salt []byte, B *big.Int) (A *big.Int, M1, M2, K []byte) {
	t.Helper()
	a, err := randInt()
	if err != nil {
		t.Fatal(err)
	}
	A = new(big.Int).Exp(g, a, N)
	x := computeX(salt, username, password)
	u := hashInt(pad(A), pad(B))
	// base = (B - k*g^x) mod N
	base := new(big.Int).Mod(new(big.Int).Sub(B, new(big.Int).Mul(k, new(big.Int).Exp(g, x, N))), N)
	S := new(big.Int).Exp(base, new(big.Int).Add(a, new(big.Int).Mul(u, x)), N)
	Sp := pad(S)
	M1 = hashBytes(pad(A), pad(B), Sp)
	M2 = hashBytes(pad(A), M1, Sp)
	K = hashBytes(Sp)
	return A, M1, M2, K
}

func mustBytes(t *testing.T, h string) []byte {
	t.Helper()
	b, err := hex.DecodeString(h)
	if err != nil {
		t.Fatalf("bad hex: %v", err)
	}
	return b
}

func mustBig(t *testing.T, h string) *big.Int {
	t.Helper()
	n, ok := new(big.Int).SetString(h, 16)
	if !ok {
		t.Fatalf("bad big hex")
	}
	return n
}

func trimLead(h string) string {
	for len(h) > 1 && h[0] == '0' {
		h = h[1:]
	}
	return h
}
